/**
 * Retrieves the eBay API Status RSS feed and refreshes docs/API_STATUS.md.
 * Used by the scheduled API-sync workflow.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

import { type EbayApiIncident, getDeveloperStatusFeed } from '@/ebay/developer/status/incident.js';
import { getErrorMessage } from '@/utils/errors.js';

const statusSnapshotLimit = 15;
const statusSnapshotPath = join(process.cwd(), 'docs', 'API_STATUS.md');

function markdownCellFor(cellText: string): string {
  return cellText.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function incidentLinkFor(apiIncident: EbayApiIncident): string {
  if (apiIncident.link.length === 0) {
    return '';
  }
  return `[Details](${apiIncident.link})`;
}

function statusMarkdownFor(apiIncidents: EbayApiIncident[]): string {
  const markdownLines: string[] = [
    '# eBay API Status (latest)',
    '',
    'Auto-updated snapshot from the [eBay API Status RSS feed](https://developer.ebay.com/rss/api-status).',
    'Full list: [developer.ebay.com/support/api-status](https://developer.ebay.com/support/api-status).',
    '',
    `*Last updated: ${new Date().toISOString()}*`,
    '',
    '| Title | API | Site | Status | Last updated | Link |',
    '|-------|-----|------|--------|--------------|------|',
  ];

  for (const apiIncident of apiIncidents) {
    markdownLines.push(
      `| ${markdownCellFor(apiIncident.title)} | ${markdownCellFor(apiIncident.api)} | ${markdownCellFor(apiIncident.site)} | ${markdownCellFor(apiIncident.status)} | ${markdownCellFor(apiIncident.lastUpdated)} | ${incidentLinkFor(apiIncident)} |`,
    );
  }

  markdownLines.push(
    '',
    '---',
    '',
    '*Generated by [ebay-mcp](https://github.com/YosefHayim/ebay-mcp) API status sync.*',
  );
  return markdownLines.join('\n');
}

const refreshStatusSnapshot = async (): Promise<number> => {
  const statusCompletion = await getDeveloperStatusFeed({ limit: statusSnapshotLimit });
  if (statusCompletion.kind === 'ebayRequestFailed') {
    throw new Error(statusCompletion.ebayFailure.message);
  }

  const apiIncidents = statusCompletion.ebayDocument.incidents;
  writeFileSync(statusSnapshotPath, statusMarkdownFor(apiIncidents), 'utf8');
  return apiIncidents.length;
};

void refreshStatusSnapshot().then(
  (incidentCount) => {
    console.log(`Wrote ${incidentCount} incidents to ${statusSnapshotPath}`);
  },
  (statusSnapshotFailure: unknown) => {
    console.error(getErrorMessage(statusSnapshotFailure, 'Failed to update eBay API status'));
    process.exitCode = 1;
  },
);
