import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const repositoryRoot = fileURLToPath(new URL('../../../', import.meta.url));
const specificationRoot = join(repositoryRoot, 'specs/ebay');
const generatedSourceRoot = join(repositoryRoot, 'src/generated/ebay');
const ungeneratedSpecificationFiles = new Set([
  join('sell-apps', 'account-management', 'sell_account_v2_oas3.json'),
]);

const specificationFiles = readdirSync(specificationRoot, {
  recursive: true,
  withFileTypes: true,
})
  .filter(
    (specificationDirent) =>
      specificationDirent.isFile() && specificationDirent.name.endsWith('_oas3.json'),
  )
  .map((specificationDirent) =>
    relative(specificationRoot, join(specificationDirent.parentPath, specificationDirent.name)),
  );

const generatedSourceFiles = readdirSync(generatedSourceRoot, {
  recursive: true,
  withFileTypes: true,
})
  .filter(
    (generatedSourceDirent) =>
      generatedSourceDirent.isFile() && generatedSourceDirent.name.endsWith('.ts'),
  )
  .map((generatedSourceDirent) =>
    relative(
      generatedSourceRoot,
      join(generatedSourceDirent.parentPath, generatedSourceDirent.name),
    ),
  );

const generatedBasenameFor = (specificationBasename: string): string =>
  basename(specificationBasename, '.json')
    .split(/[_.-]/u)
    .map((nameSegment, segmentPosition) => {
      if (segmentPosition === 0) {
        return nameSegment.toLowerCase();
      }

      return `${nameSegment.charAt(0).toUpperCase()}${nameSegment.slice(1).toLowerCase()}`;
    })
    .join('');

const expectedGeneratedSourceFor = (specificationFile: string): string =>
  join(dirname(specificationFile), `${generatedBasenameFor(basename(specificationFile))}.ts`);

describe('eBay machine-owned sources', () => {
  it('generates one TypeScript source for every valid OpenAPI specification', () => {
    const expectedGeneratedSources = specificationFiles
      .filter((specificationFile) => !ungeneratedSpecificationFiles.has(specificationFile))
      .map(expectedGeneratedSourceFor);

    expect([...generatedSourceFiles].sort()).toEqual([...expectedGeneratedSources].sort());
  });

  it('keeps every generated source visibly machine-owned', () => {
    for (const generatedSourceFile of generatedSourceFiles) {
      const generatedSource = readFileSync(join(generatedSourceRoot, generatedSourceFile), 'utf8');

      expect(generatedSource).toMatch(
        /^\/\*\*\r?\n \* This file was auto-generated by openapi-typescript\.\r?\n \* Do not make direct changes to the file\.\r?\n \*\/\r?\n/u,
      );
    }
  });

  it('documents the one eBay specification that cannot currently generate', () => {
    const accountV2Specification = readFileSync(
      join(specificationRoot, 'sell-apps/account-management/sell_account_v2_oas3.json'),
      'utf8',
    );

    expect(accountV2Specification).toContain(
      '"$ref": "#/components/schemas/SetUserPreferencesRequest"',
    );
    expect(accountV2Specification).not.toMatch(/"SetUserPreferencesRequest"\s*:/u);
  });

  it('keeps specifications and generated sources out of legacy roots', () => {
    const documentationSpecifications = readdirSync(join(repositoryRoot, 'docs'), {
      recursive: true,
      withFileTypes: true,
    }).filter(
      (documentationDirent) =>
        documentationDirent.isFile() && documentationDirent.name.endsWith('_oas3.json'),
    );

    expect(documentationSpecifications).toEqual([]);
    expect(existsSync(join(repositoryRoot, 'src/types/application-settings'))).toBe(false);
    expect(existsSync(join(repositoryRoot, 'src/types/sell-apps'))).toBe(false);
  });
});
