import type {
  SellerStandardsProfile,
  SellerStandardsProfilePath,
  SellerStandardsProfiles,
} from '@/ebay/sell/analytics/sellerStandardsProfile.js';

export const sellerStandardsProfilePath: SellerStandardsProfilePath = {
  program: 'PROGRAM_US',
  cycle: 'CURRENT',
};

export const sellerStandardsProfileDocument: SellerStandardsProfile = {
  cycle: {
    cycleType: 'CURRENT',
    evaluationDate: '2026-07-20T00:00:00.000Z',
    evaluationMonth: '2026-07',
  },
  defaultProgram: true,
  evaluationReason: 'Seller level generated by standards monthly evaluation cycle.',
  metrics: [{ metricKey: 'TRANSACTION_DEFECT_RATE', value: '0.003' }],
  program: 'PROGRAM_US',
  standardsLevel: 'TOP_RATED',
};

export const sellerStandardsProfilesDocument: SellerStandardsProfiles = {
  standardsProfiles: [sellerStandardsProfileDocument],
};
