import { describe, expect, it } from 'vitest';

import type { SellerStandardsProfile } from '@/ebay/sell/analytics/sellerStandardsProfile.js';
import { sellerStandardsProfileDocument } from '@tests/fixtures/sellerStandardsProfile.js';

import { sellerStandardsProfileCard } from './sellerStandardsProfile.js';

describe('sellerStandardsProfileCard', () => {
  it('shows the eBay profile identity, level, cycle, and named metrics', () => {
    expect(sellerStandardsProfileCard(sellerStandardsProfileDocument)).toEqual({
      archetype: 'card',
      title: 'Program Us',
      subtitle: 'Current',
      badges: [{ label: 'Top Rated', tone: 'success' }],
      sections: [
        {
          heading: 'Profile',
          fields: [
            { label: 'Cycle', value: 'Current' },
            { label: 'Evaluation date', value: '2026-07-20T00:00:00.000Z' },
            {
              label: 'Evaluation reason',
              value: 'Seller level generated by standards monthly evaluation cycle.',
            },
          ],
        },
        {
          heading: 'Metrics',
          fields: [{ label: 'Transaction Defect Rate', value: '0.003' }],
        },
      ],
    });
  });

  it('omits absent identity and unnamed metrics without invented fallbacks', () => {
    const incompleteProfile: SellerStandardsProfile = {
      metrics: [{ value: '7' }],
      standardsLevel: 'UNRECOGNIZED_LEVEL',
    };

    expect(sellerStandardsProfileCard(incompleteProfile)).toEqual({
      archetype: 'card',
      sections: [
        {
          heading: 'Profile',
          fields: [
            { label: 'Cycle', value: null },
            { label: 'Evaluation date', value: null },
            { label: 'Evaluation reason', value: null },
          ],
        },
      ],
    });
  });
});
